---
title: 'Dataviz Notebook #3'
output:
  html_document:
    df_print: paged
---

# Streamgraphs

Nous allons représenter la donnée à l'aide d'un streamgraph

## Lecture des données
```{r}
library(tidyverse)

source("helpers.R", encoding = "UTF-8")

flux <- read_csv("../data/obs_artif_conso_com_2009_2020_V2.csv")
myPalette <- readRDS("myPalette.rds")
```

## Installation de la librairie
```{r, eval = FALSE}
devtools::install_github("hrbrmstr/streamgraph")
```

## Streamgraph
Récupérons les données d'Aix en Provence :
```{r}
df <- flux %>% getStatsFlux("13001")
```

Réalisons le streamgraph sur Aix en Provence :

```{r}
library(streamgraph)

# L'ordre des inverse dans les streamgraphs
df$type <- factor(df$type, levels = c("Inconnu", "Mixte", "Activité", "Habitat"))

# Plot
df %>%
  streamgraph("type", "value", "year", sort = FALSE) %>%
  sg_axis_x(1, "Année", "%Y") %>% 
  sg_fill_manual(rev(myPalette))

```

## Fonction
Nous pouvons créer une fonction qui retourne le streamgraph de n'importe quelle commune :
```{r}
makeStream <- function(flux, codeInsee) {
  
  df <- flux %>% getStatsFlux(codeInsee)
  
  # L'ordre des inverse dans les streamgraphs
  df$type <- factor(df$type, levels = c("Inconnu", "Mixte", "Activité", "Habitat"))
  
  # Plot
  df %>%
    streamgraph("type", "value", "year", sort = FALSE) %>%
    sg_axis_x(1, "Année", "%Y") %>% 
    sg_fill_manual(rev(myPalette))
}
```

Voici le streamgraph sur Marseille :
```{r}
flux %>% makeStream("13055")
```